
// Code generated by github.com/0fv/gingen DO NOT EDIT

package 

import "github.com/gin-gonic/gin"

func initRoute(r *gin.Engine){
	
	route_bar := bar{}
	
	group_bar:= r.Group("/bar")
	group_bar.POST("/:test2",route_bar.post)
	
	group_bar.GET("/:test3",route_bar.get)
	
	group_bar.Use(route_bar.ware)
	
	init_foo2(group_bar)
	
	
	route_bar2 := bar2{}
	
	group_bar2:= r.Group("/bar2")
	group_bar2.POST("/:test2",route_bar2.post)
	
	group_bar2.GET("/:test3",route_bar2.get)
	
	group_bar2.Use(route_bar2.ware)
	
	
	route_foo := foo{}
	
	group_foo:= r.Group("/foo")
	group_foo.POST("/:test2",route_foo.post)
	
	group_foo.GET("",route_foo.get)
	
	group_foo.PUT("/update",route_foo.put)
	
	group_foo.Use(route_foo.ware)
	
	init_bar(group_foo)
	
	init_bar2(group_foo)
	
	
	route_foo2 := foo2{}
	
	group_foo2:= r.Group("/foo2")
	group_foo2.POST("/:test2",route_foo2.post)
	
	group_foo2.Use(route_foo2.ware)
	
}


func init_bar(r *gin.RouterGroup){
	
	route_bar := bar{}
	
	group_bar:= r.Group("/bar")
	group_bar.POST("/:test2",route_bar.post)
	
	group_bar.GET("/:test3",route_bar.get)
	
	group_bar.Use(route_bar.ware)
	
	init_foo2(group_bar)
	
}



func init_foo2(r *gin.RouterGroup){
	
	route_foo2 := foo2{}
	
	group_foo2:= r.Group("/foo2")
	group_foo2.POST("/:test2",route_foo2.post)
	
	group_foo2.Use(route_foo2.ware)
	
}



func init_bar2(r *gin.RouterGroup){
	
	route_bar2 := bar2{}
	
	group_bar2:= r.Group("/bar2")
	group_bar2.POST("/:test2",route_bar2.post)
	
	group_bar2.GET("/:test3",route_bar2.get)
	
	group_bar2.Use(route_bar2.ware)
	
}



func init_foo(r *gin.RouterGroup){
	
	route_foo := foo{}
	
	group_foo:= r.Group("/foo")
	group_foo.POST("/:test2",route_foo.post)
	
	group_foo.GET("",route_foo.get)
	
	group_foo.PUT("/update",route_foo.put)
	
	group_foo.Use(route_foo.ware)
	
	init_bar(group_foo)
	
	init_bar2(group_foo)
	
}



func init_bar(r *gin.RouterGroup){
	
	route_bar := bar{}
	
	group_bar:= r.Group("/bar")
	group_bar.POST("/:test2",route_bar.post)
	
	group_bar.GET("/:test3",route_bar.get)
	
	group_bar.Use(route_bar.ware)
	
	init_foo2(group_bar)
	
}



func init_foo2(r *gin.RouterGroup){
	
	route_foo2 := foo2{}
	
	group_foo2:= r.Group("/foo2")
	group_foo2.POST("/:test2",route_foo2.post)
	
	group_foo2.Use(route_foo2.ware)
	
}



func init_bar2(r *gin.RouterGroup){
	
	route_bar2 := bar2{}
	
	group_bar2:= r.Group("/bar2")
	group_bar2.POST("/:test2",route_bar2.post)
	
	group_bar2.GET("/:test3",route_bar2.get)
	
	group_bar2.Use(route_bar2.ware)
	
}



func init_foo2(r *gin.RouterGroup){
	
	route_foo2 := foo2{}
	
	group_foo2:= r.Group("/foo2")
	group_foo2.POST("/:test2",route_foo2.post)
	
	group_foo2.Use(route_foo2.ware)
	
}

