package main

import (
	"os"
	"text/template"
)

const suffix = "_route_gen.go"

const globaltpl = `
// Code generated by github.com/0fv/gingen DO NOT EDIT

package {{.pkg}}

func initRoute(r *gin.Context){
	{{range $tr=.li}}
	route_{{$tr.name}} := {{$rr.name}}{}
	group_{{$tr.name}} := r.Group({{$tr.route}})
	{{range $fun=.functionList}}
	{{if $fun.middleware}}
	group_{{$tr.name}}.Use(route_{{$tr.name}}.{{$fun.name}})
	{{else}}
	{{range $me=$fun.method}}
	group_{{$tr.name}}.{{$me}}({{$fun.route}},route_{{$fun.name}})
	{{end}}
	{{end}}
	{{end}}
	{{end}}
}
`
const grouptpl = `

`

func genRoot(rs routeList) {
	data := map[string]interface{}{
		"pkg": os.Getenv("GOPACKAGE"),
		"li":  rs,
	}
	t, err := template.New("").Parse(tpl)
	if err != nil {
		return nil, errors.Wrapf(err, "template init err")
	}

}

func gen(parent *routeInfo, info *routeInfo) {

}
